### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by mokraemer** [php/pecl-mail-imap#1]
Is there any docu on this package? What is the difference to the built-in imap support?

**Comment by derickr** [comment]
The documentation is the same as the one that is bundled with PHP. From PHP 8.4 (or 9) this extension will no longer be part of the PHP core distribution.

**Comment by mokraemer** [comment]
ok. Thanks - that was not clear to me, where this extension comes from.

**Comment by derickr** [comment]
I will add a readme after the break!
