### ISSUE TITLE
Warning in PHP 8.4.1

### ISSUE THREAD

**Issue by Pinnokkio** [php/pecl-mail-imap#13]
I've downloaded version 1.0.3 on https://pecl.php.net/package/imap, put it into `<php-dir>/ext/php_imap.dll` but whenever I check my php installation, it says:
```
php --version

PHP Warning:  PHP Startup: imap: Unable to initialize module
Module compiled with module API=20230831
PHP    compiled with module API=20240924
These options need to match
 in Unknown on line 0

Warning: PHP Startup: imap: Unable to initialize module
Module compiled with module API=20230831
PHP    compiled with module API=20240924
These options need to match
 in Unknown on line 0
PHP 8.4.1 (cli) (built: Nov 20 2024 11:13:29) (ZTS Visual C++ 2022 x64)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Xdebug v3.4.0beta1, Copyright (c) 2002-2024, by Derick Rethans
```
It says, version 1.0.3 is available for `PHP Version: PHP 8.3.0 or newer` which doesn't seem to.
Any help to fix this?

**Comment by cmb69** [comment]
Builds compatible with PHP 8.4 will be rolled out in due course, see https://news-web.php.net/php.internals.win/1313.

**Comment by cmb69** [comment]
DLLs for PHP 8.4 are now available at https://pecl.php.net/package/imap.

**Comment by Pinnokkio** [comment]
Still not available.

**Comment by cmb69** [comment]
https://pecl.php.net/package/imap/1.0.3/windows:

![imap](https://github.com/user-attachments/assets/63fe01fc-7362-47d2-afd0-a41c0c9d2cd7)

If you don't see this, there might be a caching issue. Try https://downloads.php.net/~windows/pecl/releases/imap/1.0.3/php_imap-1.0.3-8.4-ts-vs17-x64.zip (direct download link).
