### ISSUE TITLE
Windows DLL available to download

### ISSUE THREAD

**Issue by macintoshplus** [php/pecl-mail-imap#7]
I am pleased to announce that this extension is now compiled for Windows by the PHP Extension Repository site.

You can download the DLLs on the extension page: https://phpext.phptools.online/extension/mail/imap-425

If you have any questions, I am available to discuss them.

**Comment by cmb69** [comment]
@macintoshplus, as far as I know, ext/imap is removed from php-src as of PHP 8.4.0, but is still available for PHP 8.3 – the linked site states otherwise.

Anyhow, DLLs are also available from https://pecl.php.net/package/imap. I think this ticket can be closed.

**Comment by macintoshplus** [comment]
Hi,

Effectively, IMAP is provided with PHP 8.3. The information has been changed on the website.

Thank you, best regards.
